"""Column dictionary and machine-readable schema for dicom-organizer CSV outputs."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from dicom_organizer.core import (
    COMMON_METADATA_COLUMNS,
    COMMON_SUMMARY_COLUMNS,
    CT_METADATA_COLUMNS,
    CT_SUMMARY_COLUMNS,
    FILE_REPORT_COLUMNS,
    MR_METADATA_COLUMNS,
    MR_SUMMARY_COLUMNS,
    OUTPUT_SCHEMA_VERSION,
    PT_METADATA_COLUMNS,
    PT_SUMMARY_COLUMNS,
    US_METADATA_COLUMNS,
    US_SUMMARY_COLUMNS,
    XA_METADATA_COLUMNS,
    XA_SUMMARY_COLUMNS,
)


@dataclass(frozen=True)
class ColumnSpec:
    name: str
    description_en: str
    description_ja: str
    unit: str  # e.g. "ms", "mm", "deg", "T", "Hz/pixel", "s", "Bq", "kV", "mA", "W/kg", "%", "bytes", "HH:MM:SS", or ""
    source: str  # DICOM keyword/tag or "derived: ..." / "organizer: ..."
    level: str  # "image" | "series" | "file"
    missing: str  # English explanation of when the value is "N/A"
    profiles: tuple[str, ...] = ()  # Specific profile name(s), or () for common/file columns
    absent_value: str | None = None  # CSV value when header attributes are all absent, or None if always populated


COLUMN_SPECS: tuple[ColumnSpec, ...] = (
    # --- Common Metadata Columns ---
    ColumnSpec(
        name="OrganizedFileName",
        description_en="POSIX relative path of the organized file within the output directory",
        description_ja="出力ディレクトリ配下における整理後ファイルのPOSIX相対パス",
        unit="",
        source="organizer: destination path relative to output root",
        level="image",
        missing="in list-only mode (--list-only) or if file was not placed/organized",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="StudyFolder",
        description_en="POSIX relative path of the study directory from output root",
        description_ja="出力ルートからの検査フォルダのPOSIX相対パス",
        unit="",
        source="organizer: study folder path derived from layout and metadata",
        level="image",
        missing="never missing; always determined from organization layout and metadata",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="SeriesFolder",
        description_en="POSIX relative path of the series directory from output root",
        description_ja="出力ルートからのシリーズフォルダのPOSIX相対パス",
        unit="",
        source="organizer: series folder path derived from series template",
        level="image",
        missing="never missing; always determined from series folder label template",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="SeriesUID",
        description_en="Unique identifier for the Series",
        description_ja="シリーズを一意に識別するUID",
        unit="",
        source="SeriesInstanceUID (0020,000E)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="SOPInstanceUID",
        description_en="Unique identifier for the SOP Instance (image object)",
        description_ja="SOPインスタンス（画像オブジェクト）を一意に識別するUID",
        unit="",
        source="SOPInstanceUID (0008,0018)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="SeriesNumber",
        description_en="Integer number identifying the series within the study (6-digit zero-padded)",
        description_ja="検査内でのシリーズ番号（6桁ゼロ埋め整数表記）",
        unit="",
        source="SeriesNumber (0020,0011)",
        level="image",
        missing=(
            "never missing; formatted as a 6-digit zero-padded integer (e.g. '000001'), "
            "or sanitized string if non-numeric; defaults to '000000' when attribute is absent"
        ),
        profiles=(),
        absent_value="000000",
    ),
    ColumnSpec(
        name="SeriesDescription",
        description_en="User-provided or operator description of the series",
        description_ja="シリーズの記述・説明",
        unit="",
        source="SeriesDescription (0008,103E)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ProtocolName",
        description_en="User-defined description of the acquisition protocol",
        description_ja="撮像プロトコル名",
        unit="",
        source="ProtocolName (0018,1030)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="FileCount",
        description_en="Number of DICOM files belonging to the series",
        description_ja="シリーズ内のDICOMファイル総数",
        unit="",
        source="derived: count of DICOM files in series",
        level="series",
        missing="never missing in series summary; N/A prior to series aggregation",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="InstanceNumber",
        description_en="Number identifying the instance (slice/image) within the series",
        description_ja="シリーズ内のインスタンス番号（スライス番号）",
        unit="",
        source="InstanceNumber (0020,0013)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="AcquisitionDate",
        description_en="Date the acquisition of data started (YYYYMMDD)",
        description_ja="データ収集開始日（YYYYMMDD形式）",
        unit="",
        source="AcquisitionDate (0008,0022); fallback: StudyDate (0008,0020)",
        level="image",
        missing="both AcquisitionDate and StudyDate absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="AcquisitionTime",
        description_en="Time the acquisition of data started (DICOM TM format)",
        description_ja="データ収集開始時刻（DICOM TM形式）",
        unit="",
        source="AcquisitionTime (0008,0032)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="StudyDate",
        description_en="Date the study started (YYYYMMDD)",
        description_ja="検査開始日（YYYYMMDD形式）",
        unit="",
        source="StudyDate (0008,0020)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="StudyTime",
        description_en="Time the study started (DICOM TM format)",
        description_ja="検査開始時刻（DICOM TM形式）",
        unit="",
        source="StudyTime (0008,0030)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SeriesDate",
        description_en="Date the series started (YYYYMMDD)",
        description_ja="シリーズ開始日（YYYYMMDD形式）",
        unit="",
        source="SeriesDate (0008,0021)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SeriesTime",
        description_en="Time the series started (DICOM TM format)",
        description_ja="シリーズ開始時刻（DICOM TM形式）",
        unit="",
        source="SeriesTime (0008,0031)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PatientName",
        description_en="Patient's full name (pseudonymized under hash, N/A under drop)",
        description_ja="患者氏名（hash時は仮名化、drop時はN/A）",
        unit="",
        source="PatientName (0010,0010)",
        level="image",
        missing="attribute absent in the DICOM header, or --patient-mode drop",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PatientID",
        description_en="Primary hospital identifier for the patient (pseudonymized under hash, N/A under drop)",
        description_ja="患者ID（hash時は仮名化、drop時はN/A）",
        unit="",
        source="PatientID (0010,0020)",
        level="image",
        missing="attribute absent in the DICOM header, or --patient-mode drop",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PatientIDHash",
        description_en="First 16 hexadecimal characters of SHA-256 digest of PatientID",
        description_ja="患者IDのSHA-256ダイジェスト先頭16文字（drop時はN/A）",
        unit="",
        source="derived: SHA-256 digest of PatientID",
        level="image",
        missing="PatientID absent in the DICOM header, or --patient-mode drop",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PatientNameHash",
        description_en="First 16 hexadecimal characters of SHA-256 digest of PatientName",
        description_ja="患者氏名のSHA-256ダイジェスト先頭16文字（drop時はN/A）",
        unit="",
        source="derived: SHA-256 digest of PatientName",
        level="image",
        missing="PatientName absent in the DICOM header, or --patient-mode drop",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="Modality",
        description_en="Type of equipment that originally acquired data (e.g. MR, CT, US, XA, PT)",
        description_ja="撮像モダリティ種別（MR, CT, US, XA, PTなど）",
        unit="",
        source="Modality (0008,0060)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="SOPClassUID",
        description_en="Unique identifier for the SOP Class",
        description_ja="SOPクラスを一意に識別するUID",
        unit="",
        source="SOPClassUID (0008,0016)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="FOV_HxW_mm",
        description_en="Field of view height and width in mm (PixelSpacing * Rows x Columns)",
        description_ja="撮像視野サイズ（高さx幅、mm単位）",
        unit="mm",
        source="derived: PixelSpacing * (Rows x Columns)",
        level="image",
        missing="PixelSpacing, Rows, or Columns absent or non-numeric",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="Matrix_RowsxCols",
        description_en="Image matrix dimensions in pixels (RowsxColumns)",
        description_ja="画像マトリクス行列サイズ（行数x列数）",
        unit="",
        source="derived: Rows x Columns",
        level="image",
        missing="Rows or Columns absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SliceThickness_mm",
        description_en="Nominal slice thickness in mm",
        description_ja="公称スライス厚（mm単位）",
        unit="mm",
        source="SliceThickness (0018,0050); Enhanced: PixelMeasuresSequence.SliceThickness",
        level="image",
        missing="attribute absent in the header or functional groups",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SpacingBetweenSlices_mm",
        description_en="Distance between adjacent slice centers in mm along normal vector",
        description_ja="隣接スライス中心間の距離（スライス間隔、mm単位）",
        unit="mm",
        source="SpacingBetweenSlices (0018,0088); Enhanced: PixelMeasuresSequence.SpacingBetweenSlices",
        level="image",
        missing="attribute absent in the header or functional groups",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SliceLocation_mm",
        description_en="Relative position of slice in mm",
        description_ja="スライス位置の相対座標（mm単位）",
        unit="mm",
        source="SliceLocation (0020,1041)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="Manufacturer",
        description_en="Manufacturer of the equipment that produced the DICOM data",
        description_ja="装置製造メーカー名",
        unit="",
        source="Manufacturer (0008,0070)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ManufacturerModelName",
        description_en="Manufacturer's model name of the equipment",
        description_ja="装置モデル名",
        unit="",
        source="ManufacturerModelName (0008,1090)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SourceFileName",
        description_en="POSIX relative path of the source file from input root directory",
        description_ja="入力ルートディレクトリからの元ファイルのPOSIX相対パス",
        unit="",
        source="organizer: relative path of source file from input root",
        level="image",
        missing="never missing for scanned candidate files",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="ImageType",
        description_en="Image identification characteristics separated by backslashes",
        description_ja="画像識別特性（バックスラッシュ区切りの多値文字列）",
        unit="",
        source="ImageType (0008,0008)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="Rows",
        description_en="Number of rows in the image raster",
        description_ja="画像の行数（ピクセル数）",
        unit="",
        source="Rows (0028,0010)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="Columns",
        description_en="Number of columns in the image raster",
        description_ja="画像の列数（ピクセル数）",
        unit="",
        source="Columns (0028,0011)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PixelSpacing",
        description_en="Physical spacing between pixel centers (row\\column spacing in mm)",
        description_ja="ピクセル中心間距離（行間隔\\列間隔、mm単位）",
        unit="mm",
        source="PixelSpacing (0028,0030); Enhanced: PixelMeasuresSequence.PixelSpacing",
        level="image",
        missing="attribute absent in the header or functional groups",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ImagePositionPatient",
        description_en="x, y, and z coordinates of the upper left corner of the image in patient coordinates (mm)",
        description_ja="患者座標系における画像左上ピクセルのx, y, z座標（mm単位）",
        unit="mm",
        source="ImagePositionPatient (0020,0032); Enhanced: PlanePositionSequence.ImagePositionPatient",
        level="image",
        missing="attribute absent in the header or functional groups",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ImageOrientationPatient",
        description_en="Direction cosines of the first row and first column with respect to the patient",
        description_ja="患者座標系に対する画像の第1行および第1列の方向余弦",
        unit="",
        source="ImageOrientationPatient (0020,0037); Enhanced: PlaneOrientationSequence.ImageOrientationPatient",
        level="image",
        missing="attribute absent in the header or functional groups",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PatientPosition",
        description_en="Patient position descriptor relative to equipment (e.g. HFS, FFS)",
        description_ja="装置に対する患者の体位記述子（HFS, FFSなど）",
        unit="",
        source="PatientPosition (0018,5100)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="FrameOfReferenceUID",
        description_en="Unique identifier of the spatial Frame of Reference",
        description_ja="空間座標基準系（Frame of Reference）を一意に識別するUID",
        unit="",
        source="FrameOfReferenceUID (0020,0052)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="StudyInstanceUID",
        description_en="Unique identifier for the Study",
        description_ja="検査を一意に識別するUID",
        unit="",
        source="StudyInstanceUID (0020,000D)",
        level="image",
        missing="attribute absent in the DICOM header",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="IsNormalized",
        description_en="Flag indicating whether image is intensity-normalized (true/false derived from ImageType)",
        description_ja="画像が強度補正（NORM）済みかどうかを示すフラグ（true/false）",
        unit="",
        source="derived: whether ImageType contains NORM",
        level="image",
        missing=(
            "never missing; reports 'true' if ImageType contains 'NORM', "
            "otherwise 'false' (including when ImageType attribute is absent)"
        ),
        profiles=(),
        absent_value="false",
    ),
    ColumnSpec(
        name="ScanDuration",
        description_en="Total scan duration formatted as HH:MM:SS",
        description_ja="総撮像時間（スキャン所要時間、HH:MM:SS形式）",
        unit="HH:MM:SS",
        source=(
            "derived: AcquisitionDuration (0018,9073) in seconds; "
            "GE private GEMS_ACQU_01 (0019,105A) in microseconds / 1e6; "
            "or Siemens ASCCONV lTotalScanTimeSec in seconds; formatted as HH:MM:SS"
        ),
        level="image",
        missing="scan duration tag not found or non-positive",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ScanDurationSource",
        description_en="Identifier of the tag or element where scan duration was extracted",
        description_ja="撮像時間の取得元となったタグまたは要素識別子",
        unit="",
        source="derived: tag or element where scan duration was found",
        level="image",
        missing="scan duration tag not found",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="NumberOfFrames",
        description_en="Number of frames in a multi-frame DICOM object",
        description_ja="マルチフレームDICOMオブジェクトのフレーム数",
        unit="",
        source="NumberOfFrames (0028,0008)",
        level="image",
        missing="attribute absent in the DICOM header (single-frame object)",
        profiles=(),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="FrameVaryingAttributes",
        description_en=(
            "Attribute columns that vary across frames in PerFrameFunctionalGroupsSequence "
            "joined with | ('none' if identical; appends PhaseEncodingDirectionPatient "
            "at the end if orientation varies)"
        ),
        description_ja=(
            "マルチフレーム画像内でフレームごとに値が変動する列名一覧（|区切り、変動なし時はnone。"
            "向きが変動する場合は末尾にPhaseEncodingDirectionPatientが追加される）"
        ),
        unit="",
        source="derived: columns whose values vary across frames in PerFrameFunctionalGroupsSequence",
        level="image",
        missing="object has no PerFrameFunctionalGroupsSequence",
        profiles=(),
        absent_value="N/A",
    ),
    # --- MR Metadata Columns ---
    ColumnSpec(
        name="TR_ms",
        description_en="Repetition time in ms",
        description_ja="繰り返し時間（TR、ms単位）",
        unit="ms",
        source="RepetitionTime (0018,0080); Enhanced: MRTimingAndRelatedParametersSequence.RepetitionTime",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="TE_ms",
        description_en="Echo time in ms",
        description_ja="エコー時間（TE、ms単位）",
        unit="ms",
        source="EchoTime (0018,0081); Enhanced: MREchoSequence.EffectiveEchoTime",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="EchoCount",
        description_en="Number of unique echo times in the series",
        description_ja="シリーズ内のエコー数（固有TE値の件数）",
        unit="",
        source="derived: number of unique TE_ms values in the series",
        level="series",
        missing="not an MR series, or no valid echo times found in series",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="EchoTimes_ms",
        description_en="List of unique echo times in the series joined by | in ms",
        description_ja="シリーズ内の固有エコー時間一覧（|区切り、ms単位）",
        unit="ms",
        source="derived: unique TE_ms values in the series joined by |",
        level="series",
        missing="not an MR series, or no valid echo times found in series",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PixelBandwidth_Hz_per_px",
        description_en="Equivalent pixel bandwidth in Hz/pixel",
        description_ja="ピクセルあたりの等価受信帯域幅（Hz/pixel単位）",
        unit="Hz/pixel",
        source="PixelBandwidth (0018,0095); Enhanced: MRImagingModifierSequence.PixelBandwidth",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="EchoTrainLength",
        description_en="Number of lines in k-space acquired per excitation (ETL)",
        description_ja="エコートレイン長（ETL、1励起あたりのk空間充填ライン数）",
        unit="",
        source="EchoTrainLength (0018,0091); Enhanced: MRTimingAndRelatedParametersSequence.EchoTrainLength",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="FlipAngle_deg",
        description_en="Steady-state flip angle in degrees",
        description_ja="フリップ角（度単位）",
        unit="deg",
        source="FlipAngle (0018,1314); Enhanced: MRTimingAndRelatedParametersSequence.FlipAngle",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="NumberOfAverages",
        description_en="Number of times each line of k-space was acquired (NEX/averages)",
        description_ja="積算回数（加算回数、NSA/NEX）",
        unit="",
        source="NumberOfAverages (0018,0083); Enhanced: MRAveragesSequence.NumberOfAverages",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="MagneticFieldStrength_T",
        description_en="Nominal field strength of the MR magnet in Tesla",
        description_ja="静磁場強度（テスラ単位）",
        unit="T",
        source="MagneticFieldStrength (0018,0087)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ScanningSequence",
        description_en="Description of the type of data taken (e.g. SE, GE, IR, EP)",
        description_ja="スキャンシーケンス種別（SE, GE, IR, EPなど）",
        unit="",
        source="ScanningSequence (0018,0020)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SequenceVariant",
        description_en="Variant of the scanning sequence (e.g. SK, SP, SS, MTC)",
        description_ja="シーケンス変異型（SK, SP, SS, MTCなど）",
        unit="",
        source="SequenceVariant (0018,0021)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SequenceName",
        description_en="User or manufacturer sequence name",
        description_ja="シーケンス名（メーカーまたはユーザー定義）",
        unit="",
        source="SequenceName (0018,0024); Philips fallback: private sequence (2005,140F)[0].PulseSequenceName",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="InversionTime_ms",
        description_en="Inversion time in ms after 180-degree prep pulse",
        description_ja="反転時間（TI、180度パルスからの経過時間、ms単位）",
        unit="ms",
        source="InversionTime (0018,0082); Enhanced: MRModifierSequence.InversionTimes",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="EchoNumbers",
        description_en="Echo number within the sequence",
        description_ja="シーケンス内のエコー番号",
        unit="",
        source="EchoNumbers (0018,0086)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="AcquisitionMatrix",
        description_en="Dimensions of the acquired frequency and phase encoding steps",
        description_ja="収集マトリクスサイズ（周波数・位相エンコードステップ数）",
        unit="",
        source="AcquisitionMatrix (0018,1310)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="NumberOfPhaseEncodingSteps",
        description_en="Total number of phase encoding steps",
        description_ja="位相エンコードステップ総数",
        unit="",
        source="NumberOfPhaseEncodingSteps (0018,0089)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PercentSampling",
        description_en="Fraction of acquisition matrix lines sampled (percent)",
        description_ja="サンプリング率（収集マトリクスの収集割合、パーセント）",
        unit="%",
        source="PercentSampling (0018,0093)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PercentPhaseFOV",
        description_en="Ratio of phase field of view to frequency field of view (percent)",
        description_ja="位相エンコード方向視野比率（Percent Phase FOV、パーセント）",
        unit="%",
        source="PercentPhaseFieldOfView (0018,0094)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ParallelReductionFactorInPlane",
        description_en="Parallel imaging acceleration factor in-plane",
        description_ja="面内パラレルイメージング高速化倍速数（短縮係数）",
        unit="",
        source=(
            "ParallelReductionFactorInPlane (0018,9069); "
            "Enhanced: MRModifierSequence.ParallelReductionFactorInPlane; "
            "Siemens fallback: sPat.lAccelFactPE"
        ),
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SAR",
        description_en="Calculated whole body Specific Absorption Rate in W/kg",
        description_ja="全身比吸収率（SAR、W/kg）",
        unit="W/kg",
        source="SAR (0018,1316)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="InPlanePhaseEncodingDirection",
        description_en="Axes of phase encoding relative to image row and column (ROW, COL, or COLUMN)",
        description_ja="画像行・列に対する面内位相エンコード方向（ROW, COL, またはCOLUMN）",
        unit="",
        source="InPlanePhaseEncodingDirection (0018,1312); Enhanced: MRFOVGeometrySequence.InPlanePhaseEncodingDirection",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="PhaseEncodingDirectionPatient",
        description_en=(
            "Patient-relative cardinal direction arrow of phase encoding "
            "(e.g. A→P, P→A, R→L, L→R, F→H, H→F; joined with | across frames if varying)"
        ),
        description_ja="患者座標系における位相エンコード方向の主軸矢印（A→P, P→A, R→L, L→R, F→H, H→Fなど。フレーム間で変動する場合は|連結）",
        unit="",
        source="derived: patient-relative cardinal axis calculated from InPlanePhaseEncodingDirection and ImageOrientationPatient",
        level="image",
        missing="attribute absent in the header, orientation invalid, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ReceiveCoilName",
        description_en="Name of the receive coil used",
        description_ja="使用された受信コイル名",
        unit="",
        source="ReceiveCoilName (0018,1250)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="MRAcquisitionType",
        description_en="Identification of data acquisition technique (2D or 3D)",
        description_ja="MR収集技術種別（2Dまたは3D）",
        unit="",
        source="MRAcquisitionType (0018,0023)",
        level="image",
        missing="attribute absent in the header, or not an MR object",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SiemensChannelMixing",
        description_en="Siemens private channel mixing descriptor",
        description_ja="シーメンス固有チャンネルミキシング設定",
        unit="",
        source="Siemens private tag (0021,1176)",
        level="image",
        missing="attribute absent in the header, or Manufacturer does not contain 'siemens'",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SiemensCoilElement",
        description_en="Siemens private coil element identifier for the instance",
        description_ja="シーメンス固有コイルエレメント識別子",
        unit="",
        source="Siemens private tag (0021,114F)",
        level="image",
        missing="attribute absent in the header, or Manufacturer does not contain 'siemens'",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="CoilElementCount",
        description_en="Number of distinct coil elements used in the series",
        description_ja="シリーズ内で使用された固有コイルエレメント数",
        unit="",
        source="derived: number of unique SiemensCoilElement values in the series",
        level="series",
        missing="not a Siemens MR series, or no coil elements found in series",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="CoilElements",
        description_en="List of distinct coil elements in the series joined by |",
        description_ja="シリーズ内の固有コイルエレメント一覧（|区切り）",
        unit="",
        source="derived: unique SiemensCoilElement values in the series joined by |",
        level="series",
        missing="not a Siemens MR series, or no coil elements found in series",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SiemensIceDims",
        description_en="Siemens private ICE dimension string (e.g. CH_ECHO)",
        description_ja="シーメンス固有ICE次元文字列（例: CH_ECHO）",
        unit="",
        source="Siemens private tag (0021,118E)",
        level="image",
        missing="attribute absent in the header, or Manufacturer does not contain 'siemens'",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SiemensIceDimChannel",
        description_en="Siemens ICE channel dimension index parsed from SiemensIceDims",
        description_ja="SiemensIceDimsから抽出されたチャンネル次元番号",
        unit="",
        source="derived: first component of SiemensIceDims (0021,118E)",
        level="image",
        missing="SiemensIceDims absent, or Manufacturer does not contain 'siemens'",
        profiles=("mr",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SiemensIceDimEcho",
        description_en="Siemens ICE echo dimension index parsed from SiemensIceDims",
        description_ja="SiemensIceDimsから抽出されたエコー次元番号",
        unit="",
        source="derived: second component of SiemensIceDims (0021,118E)",
        level="image",
        missing="SiemensIceDims absent or lacks echo index, or Manufacturer does not contain 'siemens'",
        profiles=("mr",),
        absent_value="N/A",
    ),
    # --- CT / XA Shared Metadata Columns ---
    ColumnSpec(
        name="KVP_kV",
        description_en="Peak kilo voltage output of the X-ray generator in kV",
        description_ja="X線管電圧（ピーク管電圧、kV単位）",
        unit="kV",
        source="KVP (0018,0060)",
        level="image",
        missing="attribute absent in the header, or not a CT/XA object",
        profiles=("ct", "xa"),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="XRayTubeCurrent_mA",
        description_en="X-ray tube current in mA",
        description_ja="X線管電流（mA単位）",
        unit="mA",
        source="XRayTubeCurrent (0018,1151)",
        level="image",
        missing="attribute absent in the header, or not a CT/XA object",
        profiles=("ct", "xa"),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ExposureTime_ms",
        description_en="Exposure time in ms",
        description_ja="X線照射時間（露光時間、ms単位）",
        unit="ms",
        source="ExposureTime (0018,1150)",
        level="image",
        missing="attribute absent in the header, or not a CT/XA object",
        profiles=("ct", "xa"),
        absent_value="N/A",
    ),
    # --- CT-Specific Metadata Columns ---
    ColumnSpec(
        name="ConvolutionKernel",
        description_en="Label describing the convolution kernel or reconstruction algorithm",
        description_ja="再構成フィルタ関数（再構成関数／再構成カーネル名）",
        unit="",
        source="ConvolutionKernel (0018,1210)",
        level="image",
        missing="attribute absent in the header, or not a CT object",
        profiles=("ct",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="ReconstructionDiameter_mm",
        description_en="Diameter in mm of the region from which the image was reconstructed",
        description_ja="再構成視野直径（再構成FOV、mm単位）",
        unit="mm",
        source="ReconstructionDiameter (0018,1100)",
        level="image",
        missing="attribute absent in the header, or not a CT object",
        profiles=("ct",),
        absent_value="N/A",
    ),
    # --- US-Specific Metadata Columns ---
    ColumnSpec(
        name="TransducerData",
        description_en="Transducer information descriptor",
        description_ja="トランスデューサ（超音波プローブ）情報",
        unit="",
        source="TransducerData (0018,5010)",
        level="image",
        missing="attribute absent in the header, or not an US object",
        profiles=("us",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="TransducerType",
        description_en="Type of transducer used for ultrasound scan (e.g. SECTOR, LINEAR)",
        description_ja="超音波トランスデューサ種別（SECTOR, LINEAR等）",
        unit="",
        source="TransducerType (0018,6031)",
        level="image",
        missing="attribute absent in the header, or not an US object",
        profiles=("us",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="MechanicalIndex",
        description_en="Mechanical Index (MI) acoustic output metric",
        description_ja="超音波メカニカルインデックス（MI、音響出力指標）",
        unit="",
        source="MechanicalIndex (0018,5022)",
        level="image",
        missing="attribute absent in the header, or not an US object",
        profiles=("us",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="SoftTissueThermalIndex",
        description_en="Soft Tissue Thermal Index (TIS) acoustic output metric",
        description_ja="軟部組織サーマルインデックス（TIS、音響出力指標）",
        unit="",
        source="SoftTissueThermalIndex (0018,5027)",
        level="image",
        missing="attribute absent in the header, or not an US object",
        profiles=("us",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="BoneThermalIndex",
        description_en="Bone Thermal Index (TIB) acoustic output metric",
        description_ja="骨サーマルインデックス（TIB、音響出力指標）",
        unit="",
        source="BoneThermalIndex (0018,5024)",
        level="image",
        missing="attribute absent in the header, or not an US object",
        profiles=("us",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="CranialThermalIndex",
        description_en="Cranial Bone Thermal Index (TIC) acoustic output metric",
        description_ja="頭蓋骨サーマルインデックス（TIC、音響出力指標）",
        unit="",
        source="CranialThermalIndex (0018,5026)",
        level="image",
        missing="attribute absent in the header, or not an US object",
        profiles=("us",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="UltrasoundColorDataPresent",
        description_en="Flag indicating whether color data is present in ultrasound image",
        description_ja="超音波画像にカラーデータが含まれるかどうかのフラグ",
        unit="",
        source="UltrasoundColorDataPresent (0028,0014)",
        level="image",
        missing="attribute absent in the header, or not an US object",
        profiles=("us",),
        absent_value="N/A",
    ),
    # --- XA-Specific Metadata Columns ---
    ColumnSpec(
        name="FrameTime_ms",
        description_en="Nominal time per frame in ms for XA multi-frame image",
        description_ja="1フレームあたりの公称時間（フレーム時間、ms単位）",
        unit="ms",
        source="FrameTime (0018,1063)",
        level="image",
        missing="attribute absent in the header, or not an XA object",
        profiles=("xa",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="DistanceSourceToDetector_mm",
        description_en="Distance in mm from source to detector",
        description_ja="X線管球焦点から検出器までの距離（SID、mm単位）",
        unit="mm",
        source="DistanceSourceToDetector (0018,1110)",
        level="image",
        missing="attribute absent in the header, or not an XA object",
        profiles=("xa",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="DistanceSourceToPatient_mm",
        description_en="Distance in mm from source to isocenter/patient",
        description_ja="X線管球焦点からアイソセンタ／患者までの距離（SOD、mm単位）",
        unit="mm",
        source="DistanceSourceToPatient (0018,1111)",
        level="image",
        missing="attribute absent in the header, or not an XA object",
        profiles=("xa",),
        absent_value="N/A",
    ),
    # --- PT-Specific Metadata Columns ---
    ColumnSpec(
        name="Radiopharmaceutical",
        description_en="Name of the radiopharmaceutical agent administered",
        description_ja="投与された放射性医薬品名",
        unit="",
        source="RadiopharmaceuticalInformationSequence[0].Radiopharmaceutical (0018,0031)",
        level="image",
        missing="sequence absent in the header, or not a PT object",
        profiles=("pt",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="RadionuclideTotalDose_Bq",
        description_en="Total radionuclide dose administered in Becquerels (Bq)",
        description_ja="放射性核種の総投与放射能（ベクレル、Bq単位）",
        unit="Bq",
        source="RadiopharmaceuticalInformationSequence[0].RadionuclideTotalDose (0018,1074)",
        level="image",
        missing="sequence absent in the header, or not a PT object",
        profiles=("pt",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="RadionuclideHalfLife_s",
        description_en="Radionuclide physical half-life in seconds",
        description_ja="放射性核種の物理学的半減期（秒単位）",
        unit="s",
        source="RadiopharmaceuticalInformationSequence[0].RadionuclideHalfLife (0018,1075)",
        level="image",
        missing="sequence absent in the header, or not a PT object",
        profiles=("pt",),
        absent_value="N/A",
    ),
    ColumnSpec(
        name="DecayCorrection",
        description_en="Real-world value decay correction type (NONE, START, ADMIN)",
        description_ja="放射壊変補正の種別（NONE, START, ADMIN等）",
        unit="",
        source="DecayCorrection (0054,1102)",
        level="image",
        missing="attribute absent in the header, or not a PT object",
        profiles=("pt",),
        absent_value="N/A",
    ),
    # --- File Report Specific Columns ---
    ColumnSpec(
        name="Status",
        description_en="Processing outcome status for candidate file (organized, listed, planned, skipped, not_processed)",
        description_ja="候補ファイルの処理結果ステータス（organized, listed, planned, skipped, not_processed）",
        unit="",
        source="organizer: processing outcome status",
        level="file",
        missing="never missing (always populated with processing status)",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="Reason",
        description_en="Reason code explaining skipped, unplaced, or duplicate conflict status",
        description_ja="スキップ・未配置または重複衝突の理由コード",
        unit="",
        source="organizer: skip, unplaced, or duplicate reason code",
        level="file",
        missing="file is normally organized or listed without conflicts",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="Detail",
        description_en="Short English detail or conflict explanation",
        description_ja="ステータスまたは衝突に関する追加の英語詳細説明",
        unit="",
        source="organizer: additional explanation or conflict detail",
        level="file",
        missing="no additional detail is applicable",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="DuplicateOf",
        description_en=(
            "POSIX relative path of first-encountered matching file "
            "sharing the same SOPInstanceUID or identical content"
        ),
        description_ja="同一SOPInstanceUIDまたは同一内容を持つ最初に走査されたファイルのPOSIX相対パス",
        unit="",
        source="organizer: relative path of first-encountered file with same SOPInstanceUID or identical content",
        level="file",
        missing="file is not a duplicate of another file",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="SizeBytes",
        description_en="File size in bytes",
        description_ja="ファイルサイズ（バイト単位）",
        unit="bytes",
        source="organizer: file size in bytes from filesystem",
        level="file",
        missing="file could not be read or does not exist",
        profiles=(),
        absent_value=None,
    ),
    ColumnSpec(
        name="SHA256",
        description_en="SHA-256 hex digest of the file contents",
        description_ja="ファイル内容のSHA-256ハッシュダイジェスト",
        unit="",
        source="organizer: SHA-256 hex digest of file contents",
        level="file",
        missing="checksum not requested via --checksum and file not involved in duplicate comparison",
        profiles=(),
        absent_value=None,
    ),
)


_SPECS_BY_NAME: dict[str, ColumnSpec] = {spec.name: spec for spec in COLUMN_SPECS}


def column_spec(name: str) -> ColumnSpec:
    """Retrieve ColumnSpec for a given column name.

    Raises KeyError if column is not known.
    """
    try:
        return _SPECS_BY_NAME[name]
    except KeyError:
        raise KeyError(f"Unknown column name '{name}'") from None


def schema_document() -> dict[str, Any]:
    """Return machine-readable schema document as a dictionary suitable for JSON serialization."""
    return {
        "output_schema_version": OUTPUT_SCHEMA_VERSION,
        "conventions": {
            "missing_value": "Missing values are represented as 'N/A'.",
            "series_delimiter": "Multiple values within a series or across frames are joined with '|'.",
            "dicom_multi_value_delimiter": (
                "DICOM multi-valued elements (VM > 1) use the standard backslash '\\' delimiter."
            ),
            "dates_and_times": (
                "Dates follow DICOM DA format (YYYYMMDD); times follow DICOM TM format as-is without formatting."
            ),
            "character_encoding": (
                "CSV files are encoded in UTF-8 with BOM (utf-8-sig) for spreadsheet compatibility."
            ),
            "custom_tags": (
                "Custom tags requested via --dicom-tag appear as 'DICOM_<Keyword>' "
                "(or user-specified alias) with user-selected DICOM tag sources."
            ),
        },
        "files": {
            "dicom_parameters.csv": {
                "description": "Per-study image parameters table",
                "common_columns": list(COMMON_METADATA_COLUMNS),
                "profiles": {
                    "mr": list(MR_METADATA_COLUMNS),
                    "ct": list(CT_METADATA_COLUMNS),
                    "us": list(US_METADATA_COLUMNS),
                    "xa": list(XA_METADATA_COLUMNS),
                    "pt": list(PT_METADATA_COLUMNS),
                },
            },
            "all_dicom_parameters.csv": {
                "description": "Root-level concatenated image parameters table across all series",
                "common_columns": list(COMMON_METADATA_COLUMNS),
                "profiles": {
                    "mr": list(MR_METADATA_COLUMNS),
                    "ct": list(CT_METADATA_COLUMNS),
                    "us": list(US_METADATA_COLUMNS),
                    "xa": list(XA_METADATA_COLUMNS),
                    "pt": list(PT_METADATA_COLUMNS),
                },
            },
            "series_summary.csv": {
                "description": "Per-study series summary table",
                "common_columns": list(COMMON_SUMMARY_COLUMNS),
                "profiles": {
                    "mr": list(MR_SUMMARY_COLUMNS),
                    "ct": list(CT_SUMMARY_COLUMNS),
                    "us": list(US_SUMMARY_COLUMNS),
                    "xa": list(XA_SUMMARY_COLUMNS),
                    "pt": list(PT_SUMMARY_COLUMNS),
                },
            },
            "all_series_summary.csv": {
                "description": "Root-level concatenated series summary table across all series",
                "common_columns": list(COMMON_SUMMARY_COLUMNS),
                "profiles": {
                    "mr": list(MR_SUMMARY_COLUMNS),
                    "ct": list(CT_SUMMARY_COLUMNS),
                    "us": list(US_SUMMARY_COLUMNS),
                    "xa": list(XA_SUMMARY_COLUMNS),
                    "pt": list(PT_SUMMARY_COLUMNS),
                },
            },
            "file_report.csv": {
                "description": "Candidate file processing and traceability report",
                "columns": list(FILE_REPORT_COLUMNS),
            },
        },
        "columns": {
            spec.name: {
                "name": spec.name,
                "description_en": spec.description_en,
                "description_ja": spec.description_ja,
                "unit": spec.unit,
                "source": spec.source,
                "level": spec.level,
                "missing": spec.missing,
                "profiles": list(spec.profiles),
                "absent_value": spec.absent_value,
            }
            for spec in COLUMN_SPECS
        },
    }
